// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MarketWorkshopML.Model
{
    public class ModelInput
    {
        [ColumnName("timestamp"), LoadColumn(0)]
        public string Timestamp { get; set; }


        [ColumnName("polarity"), LoadColumn(1)]
        public float Polarity { get; set; }


        [ColumnName("open"), LoadColumn(2)]
        public float Open { get; set; }


    }
}
